
version: '2'
services:
    daspanel-engine-static:
        build:
            context: .
            dockerfile: Dockerfile
        image: daspanel/engine-static
        volumes:
            - daspanel-data:/opt/daspanel/data
        networks:
            - frontend
            - backend
        env_file:
            - daspanel.env
            - smtp.env

volumes:
    daspanel-data:
        external:
            name: daspanel-data

networks:  
  frontend:
    driver: bridge
  backend:
    driver: bridge


