#!/usr/bin/with-contenv sh

# Installation UUID must be informed
if [ -z "$DASPANEL_SYS_UUID" ]; then
    echo "***"
    echo "ERROR: You must set the env variable DASPANEL_SYS_UUID to a valid UUID"
    echo "***"
    exit 1
fi

case "$DASPANEL_WAIT_FOR_API" in
    YES|yes|Yes)
        echo "[DASPANEL] Waiting 60 seconds for API: $0" >&2
        /opt/daspanel/bin/wait-for-api -t 60 $DASPANEL_SYS_APISERVER/info/status
        result=$?
        if [ ! $result -eq 0 ] ; then
            echo "[DASPANEL] Can not connect to API: $DASPANEL_SYS_APISERVER/info/status" >&2
            exit 1
        fi
        ;;
    *) 
        echo "[DASPANEL] Container not need to wait API become online: $0" >&2
        exit 1
        ;;
esac

# Get system configs from API server and set env variables
SYSCFG=$(wget -O- --header=Content-Type:application/json --header="Authorization: $DASPANEL_SYS_APIKEY" "$DASPANEL_SYS_APISERVER/tenants/$DASPANEL_SYS_UUID")
result=$?
if [ ! $result -eq 0 ] ; then
    echo "[DASPANEL] Unable to get tenant configuration from API server: $0" >&2
    exit 1
fi
export DASPANEL_SYS_HOSTNAME=`echo $SYSCFG | /opt/daspanel/bin/jq -r '.sys.hostname'`
export CONSOLE_ADMIN=`echo $SYSCFG | /opt/daspanel/bin/jq -r '.sys.admin'`
export CONSOLE_PWD=`echo $SYSCFG | /opt/daspanel/bin/jq -r '.sys.password'`
export ENGINE="static"

cd /opt/daspanel/data/$DASPANEL_SYS_UUID/content

exec su-exec daspanel:daspanel /usr/sbin/gotty \
    --address=127.0.0.1 \
    --port=7681 \
    --permit-write \
    --ws-origin ".*" \
    --title-format="Daspanel Console (engine-$ENGINE) - $DASPANEL_SYS_HOSTNAME" \
    --credential=$CONSOLE_ADMIN:$CONSOLE_PWD /opt/daspanel/bin/engine-static/daspanel-console

